# Generated by Django 3.2.6 on 2021-08-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wayahead', '0002_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='deflevel',
            new_name='difficulty',
        ),
    ]
