# Generated by Django 3.2.6 on 2021-09-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wayahead', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='not_seen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='completed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed',
            field=models.ManyToManyField(related_name='completed', to='Wayahead.Question'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='review',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review',
            field=models.ManyToManyField(related_name='review', to='Wayahead.Question'),
        ),
    ]
