# Generated by Django 3.2.6 on 2021-09-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wayahead', '0006_auto_20210908_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
    ]
